version: '3'
services: 
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./laravel:/var/www/laravel
            - ./empathy:/var/www/empathy
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/logs:/var/log/nginx
    php:
        build:
            context: ./docker/php
        volumes:
            - ./laravel:/var/www/laravel
            - ./empathy:/var/www/empathy
#            - .env:/var/www/laravel/.env
    postgres:
        image: postgres
        ports:
            - "5432:5432"
        volumes:
            - ./scripts:/docker-entrypoint-initdb.d
            - pg-data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: mailman
            POSTGRES_USER: mailman
            POSTGRES_PASSWORD: n4fMqzHEv8T8
#    mariadb:
#        image: mariadb
#        restart: always
#        environment:
#            MYSQL_ROOT_PASSWORD: n4fMqzHEv8T8
#            MYSQL_DATABASE: mailman
#            MYSQL_USER: mailman
#            MYSQL_PASSWORD: 76krQcvC4ggB
    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8080
    mailcatcher:
        image: schickling/mailcatcher
        ports:
            - 1080:1080
    mailman-core:
        image: maxking/mailman-core:0.3
        ports:
            - 8001:8001
        volumes:
            - ./docker/mailman/core:/opt/mailman/
        stop_grace_period: 30s
        environment:
            - DATABASE_URL=postgres://mailman:n4fMqzHEv8T8@postgres/mailman
            - DATABASE_TYPE=postgres
            - DATABASE_CLASS=mailman.database.postgresql.PostgreSQLDatabase
            - HYPERKITTY_API_KEY=someapikey
            - MM_HOSTNAME=mailman-core
            - SMTP_HOST=mailcatcher
            - SMTP_PORT=1025
    mailman-web:
        image: maxking/mailman-web:0.3
        ports:
            - 8000:8000
        volumes:
            - ./docker/mailman/web:/opt/mailman-web-data
        stop_grace_period: 30s
        environment:
            - DATABASE_URL=postgres://mailman:n4fMqzHEv8T8@postgres/mailman
            - DATABASE_TYPE=postgres
            - DATABASE_CLASS=mailman.database.postgresql.PostgreSQLDatabase
            - HYPERKITTY_API_KEY=someapikey
            - MM_HOSTNAME=mailman-core
            - SMTP_HOST=mailcatcher
            - SMTP_PORT=1025
            - SECRET_KEY=0NCJQ5GlFCcZEAbcqDWRREVeH9Jyrlpx
            - UWSGI_STATIC_MAP=/static=/opt/mailman-web-data/static
            - MAILMAN_HOST_IP=172.22.0.2

volumes:
    pg-data:
        driver: local
