version: '3'
services: 
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./laravel:/var/www/laravel
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/logs:/var/log/nginx
    php:
        build:
            context: ./docker/php
        volumes:
            - ./laravel:/var/www/laravel
#            - .env:/var/www/laravel/.env
#    postgres:
#        image: postgres
#        ports:
#            - "5432:5432"
#        volumes:
#            - ./scripts:/docker-entrypoint-initdb.d
#        environment:
#            POSTGRES_DB: "${DB_NAME}"
#            POSTGRES_USER: "${DB_USER}"
#            POSTGRES_PASSWORD: "${DB_PASS}"
    mariadb:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: n4fMqzHEv8T8
            MYSQL_DATABASE: mailman
            MYSQL_USER: mailman
            MYSQL_PASSWORD: 76krQcvC4ggB
    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8080